/**
 * Data loader — optimized for fast server-side reads.
 *
 * OPTIMIZATIONS (vs original):
 * 1. Split remedies.json into a lightweight index (for list endpoints) and
 *    the full record map (for detail endpoints). The list endpoint no longer
 *    loads the 20MB file's `full` field — only names + truncated keynotes.
 * 2. Build an in-memory Map keyed by `id` for O(1) detail lookups (was O(n)
 *    Array.find on every request).
 * 3. Build author/letter indexes at load time so filtering is fast.
 * 4. Cache the parsed JSON in module-level variables (survives across
 *    requests in the same Node.js process).
 * 5. NEVER build a giant search-index string — use substring matching on
 *    pre-truncated fields instead.
 *
 * Files:
 *   /data/remedies.json              — original (untouched, source of truth)
 *   /data/remedies-index.json        — lightweight list index (auto-built)
 *   /data/remedies-by-id.json        — full records keyed by id (auto-built)
 *
 * The split files are generated by /scripts/build-remedy-index.py and
 * committed to the repo so Vercel doesn't need to rebuild on cold start.
 */
import fs from 'fs/promises';
import path from 'path';

const DATA_DIR = path.join(process.cwd(), 'data');
const DATA_DIR_ALT = '/home/z/my-project/data';

// ============================================================
// Module-level caches — survive across requests in same process
// ============================================================

// Lightweight index for LIST endpoint — only id/name/common/author/letter/
// chapter/organ/keynote(truncated to 200 chars). ~3MB vs 20MB.
let _remediesIndex: RemediesListItem[] | null = null;

// Full records keyed by id — for DETAIL endpoint. Built lazily.
let _remediesById: Map<string, RemedyRecord> | null = null;

// Author index — for fast filtering by author
let _remediesByAuthor: Map<string, RemediesListItem[]> | null = null;

// Letter index — for fast filtering by first letter
let _remediesByLetter: Map<string, RemediesListItem[]> | null = null;

let _rubrics: any[] | null = null;
let _therapeutics: any = null;
let _predictive: any = null;
let _synthesis: any = null;

// ============================================================
// Types
// ============================================================
export interface RemediesListItem {
  id: string;
  name: string;
  common?: string;
  author: string;
  letter?: string;
  chapter?: string;
  organ?: string;
  keynote?: string; // truncated to 200 chars
}

export interface RemedyRecord extends RemediesListItem {
  modalities?: string;
  constitution?: string;
  relationships?: string;
  dose?: string;
  full?: string;
}

// ============================================================
// Helpers
// ============================================================
async function readJson(p: string): Promise<any> {
  try {
    const buf = await fs.readFile(p);
    return JSON.parse(buf.toString('utf-8'));
  } catch (e1: any) {
    if (e1.code === 'ENOENT' && p !== DATA_DIR_ALT) {
      const altP = path.join(DATA_DIR_ALT, path.basename(p));
      const buf = await fs.readFile(altP);
      return JSON.parse(buf.toString('utf-8'));
    }
    throw e1;
  }
}

async function fileExists(p: string): Promise<boolean> {
  try {
    await fs.access(p);
    return true;
  } catch {
    return false;
  }
}

// ============================================================
// LIST ENDPOINT DATA — lightweight index
// ============================================================
export async function getRemediesIndex(): Promise<RemediesListItem[]> {
  if (_remediesIndex) return _remediesIndex;

  // Try the pre-built index first (fast — ~3MB)
  const indexPath = path.join(DATA_DIR, 'remedies-index.json');
  if (await fileExists(indexPath)) {
    _remediesIndex = await readJson(indexPath);
    return _remediesIndex!;
  }

  // Fallback: build index from full remedies.json (slower first time)
  const all = await readJson(path.join(DATA_DIR, 'remedies.json'));
  _remediesIndex = all.map((r: any) => ({
    id: r.id,
    name: r.name,
    common: r.common,
    author: r.author,
    letter: r.letter,
    chapter: r.chapter,
    organ: r.organ,
    keynote: r.keynote ? r.keynote.substring(0, 200) : '',
  }));
  return _remediesIndex!;
}

// ============================================================
// DETAIL ENDPOINT DATA — full records keyed by id (O(1) lookup)
// ============================================================
export async function getRemedyById(id: string): Promise<RemedyRecord | null> {
  if (!_remediesById) {
    // Try pre-built by-id map first
    const byIdPath = path.join(DATA_DIR, 'remedies-by-id.json');
    if (await fileExists(byIdPath)) {
      const obj = await readJson(byIdPath);
      _remediesById = new Map(Object.entries(obj));
    } else {
      // Fallback: load full remedies.json and build the map
      const all = await readJson(path.join(DATA_DIR, 'remedies.json'));
      _remediesById = new Map();
      for (const r of all) {
        _remediesById.set(r.id, r);
      }
    }
  }
  return _remediesById.get(id) || null;
}

// ============================================================
// FILTERED LIST — uses author/letter indexes for speed
// ============================================================
export async function listRemedies(opts: {
  q?: string;
  author?: string;
  letter?: string;
  offset?: number;
  limit?: number;
} = {}): Promise<{ total: number; items: RemediesListItem[] }> {
  const index = await getRemediesIndex();

  let filtered: RemediesListItem[] = index;

  if (opts.author) {
    // Build author index lazily
    if (!_remediesByAuthor) {
      _remediesByAuthor = new Map();
      for (const r of index) {
        const a = r.author || 'Unknown';
        if (!_remediesByAuthor.has(a)) _remediesByAuthor.set(a, []);
        _remediesByAuthor.get(a)!.push(r);
      }
    }
    filtered = _remediesByAuthor.get(opts.author) || [];
  }

  if (opts.letter) {
    if (!_remediesByLetter) {
      _remediesByLetter = new Map();
      for (const r of (opts.author ? filtered : index)) {
        const L = (r.letter || r.name[0]?.toUpperCase() || '?');
        if (!_remediesByLetter.has(L)) _remediesByLetter.set(L, []);
        _remediesByLetter.get(L)!.push(r);
      }
    }
    // If we already filtered by author, we need to filter the author subset
    filtered = opts.author
      ? filtered.filter(r => (r.letter || r.name[0]?.toUpperCase()) === opts.letter)
      : (_remediesByLetter.get(opts.letter) || []);
  }

  if (opts.q) {
    const q = opts.q.toLowerCase();
    // Filter on truncated fields only (fast — no `full` field access)
    filtered = filtered.filter(r =>
      (r.name + ' ' + (r.common || '') + ' ' + (r.keynote || '')).toLowerCase().includes(q)
    );
  }

  const total = filtered.length;
  const offset = opts.offset || 0;
  const limit = opts.limit || 50;
  const items = filtered.slice(offset, offset + limit);

  return { total, items };
}

// ============================================================
// LEGACY COMPAT — getRemedies() still works but loads full data
// Only use when you really need the full `full` field of every record.
// ============================================================
let _allRemediesFull: RemedyRecord[] | null = null;
export async function getRemedies(): Promise<RemedyRecord[]> {
  if (_allRemediesFull) return _allRemediesFull;
  // If we already have the by-id map, convert it to array
  if (_remediesById) {
    _allRemediesFull = Array.from(_remediesById.values());
    return _allRemediesFull;
  }
  _allRemediesFull = await readJson(path.join(DATA_DIR, 'remedies.json'));
  // Also populate _remediesById for future calls
  _remediesById = new Map();
  for (const r of _allRemediesFull) {
    _remediesById.set(r.id, r);
  }
  return _allRemediesFull!;
}

// ============================================================
// Other data loaders (unchanged)
// ============================================================
export async function getRubrics(): Promise<any[]> {
  if (_rubrics) return _rubrics;
  _rubrics = await readJson(path.join(DATA_DIR, 'rubrics.json'));
  return _rubrics!;
}

export async function getTherapeutics(): Promise<any> {
  if (_therapeutics) return _therapeutics;
  _therapeutics = await readJson(path.join(DATA_DIR, 'therapeutics.json'));
  return _therapeutics;
}

export async function getPredictive(): Promise<any> {
  if (_predictive) return _predictive;
  _predictive = await readJson(path.join(DATA_DIR, 'predictive_chapters.json'));
  return _predictive;
}

export async function getSynthesis(): Promise<any> {
  if (_synthesis) return _synthesis;
  _synthesis = await readJson(path.join(DATA_DIR, 'synthesis_rubrics.json'));
  return _synthesis;
}

// ============================================================
// Search index — only over short fields, NOT the full text.
// Original code built a 15MB string array which killed performance.
// ============================================================
export type SearchEntry = {
  type: 'remedy' | 'rubric';
  id: string;
  name: string;
  author: string;
  text: string; // short fields only
};

let _searchIndex: SearchEntry[] | null = null;
export async function getSearchIndex(): Promise<SearchEntry[]> {
  if (_searchIndex) return _searchIndex;
  const [remedies, rubrics] = await Promise.all([getRemediesIndex(), getRubrics()]);
  _searchIndex = [];
  for (const r of remedies) {
    _searchIndex.push({
      type: 'remedy',
      id: r.id,
      name: r.name,
      author: r.author || '',
      // Use only short fields — no `full` text (was 4KB avg per remedy)
      text: (r.name + ' ' + (r.common || '') + ' ' + (r.keynote || '')).toLowerCase(),
    });
  }
  for (const r of rubrics) {
    _searchIndex.push({
      type: 'rubric',
      id: r.id,
      name: r.title,
      author: r.author || '',
      text: (r.title + ' ' + (r.path || '')).toLowerCase(),
    });
  }
  return _searchIndex;
}
