const SecurityModule=(function(){let _csrf=null,_st=null,_pe=true,_ps=['materia','repertory','therapeutics','irap','roh','synthesis','favorites','notes','history','settings'];const A='/api/security';
async function init(){iCSS();try{const r=await fetch(A+'?action=config',{credentials:'include'});const d=await r.json();_pe=d.protection_enabled;_ps=d.protected_sections||_ps;if(!_csrf){const r2=await fetch(A+'?action=csrf',{credentials:'include'});_csrf=(await r2.json()).csrf;}}catch(e){console.error('[Sec]',e);_pe=false;}hNav();const av=document.querySelector('.view.active');if(av)checkP(av.id.replace('view-',''));}
function iCSS(){if(document.getElementById('s'))return;const s=document.createElement('style');s.id='s';s.textContent='.sec-overlay{position:fixed;inset:0;background:rgba(15,25,20,.92);z-index:10000;display:flex;align-items:center;justify-content:center;padding:20px}.sec-modal{background:#fff;border-radius:12px;padding:32px;max-width:400px;width:100%}.sec-title{font-family:Fraunces,serif;font-size:1.6rem;color:#1d3a2b;text-align:center;margin:0 0 8px}.sec-sub{font-size:.85rem;color:#666;text-align:center;margin:0 0 24px}.sec-input{width:100%;padding:14px;border:2px solid #e0d8c8;border-radius:8px;font-size:1.1rem;text-align:center;letter-spacing:.3em;margin-bottom:12px;font-family:monospace}.sec-btn{width:100%;padding:12px;background:#1d3a2b;color:#fff;border:none;border-radius:8px;font-weight:600;cursor:pointer}.sec-btn:hover{opacity:.85}.sec-btn-sec{background:transparent;color:#666;border:1px solid #ccc;margin-top:8px}.sec-err{color:#c44;font-size:.82rem;text-align:center;margin:8px 0;min-height:20px}.sec-link{display:block;text-align:center;margin-top:16px;color:#b8860b;font-size:.82rem;cursor:pointer}';document.head.appendChild(s);}
function hNav(){if(typeof window.switchView==='function'&&!window._sh){window._osv=window.switchView;window.switchView=function(n){if(!checkP(n))return;return window._osv.call(this,n);};window._sh=true;}}
function checkP(v){if(!_pe||!_ps.includes(v)||_st==='user'||_st==='admin')return true;showO(v);return false;}
function showO(tv){document.getElementById('sec-overlay')?.remove();const o=document.createElement('div');o.id='sec-overlay';o.className='sec-overlay';o.innerHTML='<div class="sec-modal"><h2 class="sec-title">Access Code Required</h2><p class="sec-sub">Enter 6-digit code</p><input type="password" class="sec-input" id="sec-code" maxlength="6" placeholder="------" inputmode="numeric"/><div class="sec-err" id="sec-err"></div><button class="sec-btn" onclick="SecurityModule.submit(\''+tv+'\')">Unlock</button><button class="sec-btn sec-btn-sec" onclick="SecurityModule.forgot(\''+tv+'\')">Forgot code?</button></div>';document.body.appendChild(o);setTimeout(()=>document.getElementById('sec-code')?.focus(),100);}
async function submit(tv){const c=document.getElementById('sec-code').value.trim();const e=document.getElementById('sec-err');if(!/^\d{6}$/.test(c)){e.textContent='6 digits required.';return;}try{const r=await fetch(A+'?action=verify_user',{credentials:'include',method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':_csrf||''},body:JSON.stringify({code:c,_csrf})});const d=await r.json();if(d.success){_st='user';_csrf=d.csrf;document.getElementById('sec-overlay')?.remove();if(window._osv)window._osv.call(window,tv);}else{e.textContent=d.error||'Invalid.';document.getElementById('sec-code').value='';}}catch(ex){e.textContent='Connection error.';}}
async function forgot(tv){const a=prompt("What's your favourite food?");if(!a)return;try{const r=await fetch(A+'?action=verify_answer',{credentials:'include',method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':_csrf||''},body:JSON.stringify({answer:a,_csrf})});const d=await r.json();if(d.success){_csrf=d.csrf;const nc=prompt('New 6-digit code:');if(!/^\d{6}$/.test(nc)){alert('6 digits required.');return;}const r2=await fetch(A+'?action=reset_code',{credentials:'include',method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':_csrf},body:JSON.stringify({new_code:nc,_csrf})});if((await r2.json()).success){alert('Code reset!');showO(tv);}else alert('Failed.');}else alert(d.error||'Wrong answer.');}catch(ex){alert('Connection error.');}}
return{init,submit,forgot,showO};})();window.SecurityModule=SecurityModule;
